server:
  port: 8001
spring:
  application:
    name: springcloud-producer-rest
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer2:8090/eureka/

    #zipkin:
     # base-url: http://localhost:8003