server:
  port: 10001
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 123456
    keyStoreType: PKCS12
    keyAlias: tomcat
spring:
  application:
    name: springcloud-server-api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://peer1:10000/eureka/,http://peer2:20000/eureka/,http://peer3:30000/eureka/
      #defaultZone: http://discovery:8760/eureka/,http://discovery1:8761/eureka/,http://discovery2:8762/eureka/

zuul:
  routes:
    api-image:
      path: /image/**
      serviceId: base-service-image
    api-sso:
      path: /sso/**
      serviceId: sso-server
    api-crm:
      path: /crm/**
      serviceId: crm-server