server:
  port: 10000
spring:
  application:
    name: springcloud-server-api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8080/eureka/

zuul:
  ignoredPatterns: /**/admin/**
  routes:
    host:
      connectTimeoutMillis: 5000
      socketTimeoutMillis: 15000
    api-image:
      path: /api/base/service/image/**
      serviceId: base-service-image
    #ribbon:
    #  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule # 配置服务端负载均衡策略