server:
  port: 10000

eureka:
  server:
      enable-self-preservation: false # 由于很容易出发eureka server自我保护机制，使得注册中心的服务不能够正常下线，关闭自我保护机制，以确保注册中心可以将不可用的服务正确剔除
  instance:
    hostname: peer1
    leaseRenewalIntervalInSeconds: 45 # 用于定义服务续约任务的调用间隔时间，默认30秒
    leaseExpirationDurationInSeconds: 90  # 用于定义服务失效的时间 ，默认90秒
    # instance-id: ${spring.application.name}:${random.int} # 相同服务不同实例
    #prefer-ip-address: true  # 如果不想用peer1这样的主机名称命名服务，也可以 解注释 prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://peer1:10000/eureka/,http://peer2:20000/eureka/,http://peer3:30000/eureka/
spring:
  application:
    name: springcloud-eureka-server



