server:
  port: 30000

eureka:
  instance:
    hostname: peer1
    # instance-id: ${spring.application.name}:${random.int} # 相同服务不同实例
    #prefer-ip-address: true  # 如果不想用peer1这样的主机名称命名服务，也可以 解注释 prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://peer1:10000/eureka/,http://peer2:20000/eureka/,http://peer3:30000/eureka/
spring:
  application:
    name: springcloud-eureka-server


