server:
  port: 8090

eureka:
  instance:
    hostname: peer2
    instance-id: ${spring.application.name}:${random.int} # 相同服务不同实例
  client:
    serviceUrl:
      defaultZone: http://peer1:8080/eureka/
spring:
  application:
    name: springcloud-eureka-server

