server:
  port: 8001

spring:
  application:
    name: springcloud-server-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shiyuan2he/springcloud
          search-paths: springcloud-repo-config
          username:
          password:
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://peer1:8080/eureka/