server:
  port: 8001
management:
  security:
    enabled: false
spring:
  application:
    name: springcloud-server-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shiyuan2he/springcloud
          search-paths: springcloud-repo-config
          username:
          password:
          force-pull: true
      label: master
  #rabbitmq:
   # host: 192.168.175.128
    #port: 5672
    #username: admin
   # password: admin
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8760/eureka/,http://discovery1:8761/eureka/,http://discovery2:8762/eureka/