server:
  port: 8040
spring:
  application:
    name: springcloud-service-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: springcloud-consumer-ribbon
    api-b:
      path: /api-b/**
      serviceId: springcloud-consumer-feign
